#####################################################
#        _      _                            _
#    ___(_) ___| | ___ __ ___   __ _ _ __   (_) ___
#   / __| |/ _ \ |/ / '_ ` _ \ / _` | '_ \  | |/ _ \
#   \__ \ |  __/   <| | | | | | (_| | | | |_| | (_) |
#   |___/_|\___|_|\_\_| |_| |_|\__,_|_| |_(_)_|\___/
#                  <Project name>
#              Created by Jouke Siekman
#             Netherlands 2023 Leerbroek
#                https://siekman.io
#####################################################
## <DETAILS ABOUT FILE>
#####################################################

---

 - name: Name of Playbook
   hosts: all
   become: true
   become_user: root
   vars:
    favcolor: blue
   vars_files:
    - vars.yml
   tasks: 
    - name: first-task
      include_tasks: task.yml