#####################################################
#        _      _                            _
#    ___(_) ___| | ___ __ ___   __ _ _ __   (_) ___
#   / __| |/ _ \ |/ / '_ ` _ \ / _` | '_ \  | |/ _ \
#   \__ \ |  __/   <| | | | | | (_| | | | |_| | (_) |
#   |___/_|\___|_|\_\_| |_| |_|\__,_|_| |_(_)_|\___/
#         Configure BigStorage on VPS TransIP
#              Created by Jouke Siekman
#             Netherlands 2023 Leerbroek
#                https://siekman.io
#####################################################
## Configure BigStorage on TransIP VPS 
#####################################################

--- 

    - name: Format and create filesystem ext4
      command: "{{ item }}" 
      with_items:
        - " parted -s --align optimal /dev/{{disk}} -- mklabel gpt mkpart primary 4MiB 100% "
        - " mkfs -t ext4 /dev/{{disk}}1 "

    - name: Create directory | BigStorage
      file:
       path: "{{bigstorage_dir}}"
       state: directory
      
    - name: Add a line to a file if the file does not exist, without passing regexp
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "/dev/{{disk}}1 {{bigstorage_dir}} ext4 defaults 0 0"
    
    - name: Mount up device
      ansible.posix.mount:
        path: "{{bigstorage_dir}}"
        src: /dev/{{disk}}1
        fstype: ext4
        state: present