#####################################################
# ANSIBLE-PLAYBOOK CREATE-PLAYBOOK
#####################################################
#        _      _                            _
#    ___(_) ___| | ___ __ ___   __ _ _ __   (_) ___
#   / __| |/ _ \ |/ / '_ ` _ \ / _` | '_ \  | |/ _ \
#   \__ \ |  __/   <| | | | | | (_| | | | |_| | (_) |
#   |___/_|\___|_|\_\_| |_| |_|\__,_|_| |_(_)_|\___/                 
#
#              Created by Jouke Siekman
#             Netherlands 2023 Leerbroek
#                https://siekman.io
#
#####################################################
## Create a new playbook
#####################################################
---
  - name: Create a new playbook
    hosts: all
    become: false
    become_user: root
    vars:
      favcolor: blue
    vars_files:
      - ./vars/main.yml

    vars_prompt:
      - name: playbook_name
        prompt: Name of the playbook to create?
        private: no

      - name: playbook_details
        prompt: Specify some details for this playbook?
        private: no
      
      - name: playbook_description
        prompt: Do you want to add a description to the playbook? It can also added later.
        private: no

    tasks:      
      - name: Include tasks
        include_tasks: ./tasks/main.yml