#####################################################
# ANSIBLE-PLAYBOOK 
#####################################################
#        _      _                            _
#    ___(_) ___| | ___ __ ___   __ _ _ __   (_) ___
#   / __| |/ _ \ |/ / '_ ` _ \ / _` | '_ \  | |/ _ \
#   \__ \ |  __/   <| | | | | | (_| | | | |_| | (_) |
#   |___/_|\___|_|\_\_| |_| |_|\__,_|_| |_(_)_|\___/                 
#
#              Created by Jouke Siekman
#             Netherlands 2023 Leerbroek
#                https://siekman.io
#
#####################################################
## TASKS : Install snmp when RedHat
#####################################################
---


    - name: Install packages AlmaLinux / Arch
      ansible.builtin.dnf:
        name: 
          - net-snmp
          - net-snmp-utils
        state: present
      when:
        - ansible_pkg_mgr == "dnf"

    - name: Install packages CentOS/RetHat Servers
      ansible.builtin.yum:
        name: 
          - net-snmp
          - net-snmp-utils
        state: present
      when:
        - ansible_pkg_mgr == "yum"
