#####################################################
# ANSIBLE-PLAYBOOK 
#####################################################
#        _      _                            _
#    ___(_) ___| | ___ __ ___   __ _ _ __   (_) ___
#   / __| |/ _ \ |/ / '_ ` _ \ / _` | '_ \  | |/ _ \
#   \__ \ |  __/   <| | | | | | (_| | | | |_| | (_) |
#   |___/_|\___|_|\_\_| |_| |_|\__,_|_| |_(_)_|\___/                 
#
#              Created by Jouke Siekman
#             Netherlands 2023 Leerbroek
#                https://siekman.io
#
#####################################################
## Create default directory's for playbook
#####################################################
---

    - name: Create ansible.cfg
      copy:
       dest: "{{directory}}/{{playbook_name}}/ansible.cfg"
       content: |
         #####################################################
         # ANSIBLE-PLAYBOOK {{playbook_name}}
         #####################################################
         #        _      _                            _
         #    ___(_) ___| | ___ __ ___   __ _ _ __   (_) ___
         #   / __| |/ _ \ |/ / '_ ` _ \ / _` | '_ \  | |/ _ \
         #   \__ \ |  __/   <| | | | | | (_| | | | |_| | (_) |
         #   |___/_|\___|_|\_\_| |_| |_|\__,_|_| |_(_)_|\___/                 
         #
         #              Created by Jouke Siekman
         #             Netherlands 2023 Leerbroek
         #                https://siekman.io
         #
         #####################################################
         ## Ansible.cfg: {{playbook_name}}
         #####################################################


         [defaults]
         # Use host file in folder when use a default inventory just comment it out
         inventory = ./inventory

         # Host key checking (off for networkdevices and dev)
         # host_key_checking = False