#####################################################
# ANSIBLE-PLAYBOOK 
#####################################################
#        _      _                            _
#    ___(_) ___| | ___ __ ___   __ _ _ __   (_) ___
#   / __| |/ _ \ |/ / '_ ` _ \ / _` | '_ \  | |/ _ \
#   \__ \ |  __/   <| | | | | | (_| | | | |_| | (_) |
#   |___/_|\___|_|\_\_| |_| |_|\__,_|_| |_(_)_|\___/                 
#
#              Created by Jouke Siekman
#             Netherlands 2023 Leerbroek
#                https://siekman.io
#
#####################################################
## TASKS : TEMPLATE
#####################################################
---

    - name: Create Directory's
      include_tasks: create-directory.yml

    - name: Create README.MD
      include_tasks: create-readme-md.yml
    
    - name: Create playbook 
      include_tasks: create-playbookfile.yml
    
    - name: Create ansible.cfg 
      include_tasks: create-ansible-cfg.yml

    - name: Create inventory
      include_tasks: create-inventory.yml
    
    - name: Create defaults main.yml 
      include_tasks: create-defaults-main.yml
    
    - name: Create tasks main.yml 
      include_tasks: create-tasks-main.yml

    - name: Create roles main.yml 
      include_tasks: create-roles-main.yml

    - name: Create vars main.yml 
      include_tasks: create-vars-main.yml