#####################################################
# ANSIBLE-PLAYBOOK 
#####################################################
#        _      _                            _
#    ___(_) ___| | ___ __ ___   __ _ _ __   (_) ___
#   / __| |/ _ \ |/ / '_ ` _ \ / _` | '_ \  | |/ _ \
#   \__ \ |  __/   <| | | | | | (_| | | | |_| | (_) |
#   |___/_|\___|_|\_\_| |_| |_|\__,_|_| |_(_)_|\___/                 
#
#              Created by Jouke Siekman
#             Netherlands 2023 Leerbroek
#                https://siekman.io
#
#####################################################
## Create default directory's for playbook
#####################################################
---

    - name: Create playbook file
      copy:
       dest: "{{directory}}/{{playbook_name}}/{{playbook_name}}.yml"
       content: |
         #####################################################
         # ANSIBLE-PLAYBOOK {{playbook_name}}
         #####################################################
         #        _      _                            _
         #    ___(_) ___| | ___ __ ___   __ _ _ __   (_) ___
         #   / __| |/ _ \ |/ / '_ ` _ \ / _` | '_ \  | |/ _ \
         #   \__ \ |  __/   <| | | | | | (_| | | | |_| | (_) |
         #   |___/_|\___|_|\_\_| |_| |_|\__,_|_| |_(_)_|\___/                 
         #
         #              Created by Jouke Siekman
         #             Netherlands {{year}} Leerbroek
         #                https://siekman.io
         #
         #####################################################
         ## PLAYBOOK: {{playbook_name}}
         #####################################################
         ---

          - name: {{playbook_name}} {{playbook_details}}
            hosts: all
            become: false
            become_user: root
            vars:
              favcolor: blue
            vars_files:
              - ./vars/main.yml

            tasks:      
              - name: Include tasks
                include_tasks: ./tasks/main.yml
         
            roles:      
              - name: Include roles
                include_roles: ./roles/main.yml