#####################################################
#        _      _                            _
#    ___(_) ___| | ___ __ ___   __ _ _ __   (_) ___
#   / __| |/ _ \ |/ / '_ ` _ \ / _` | '_ \  | |/ _ \
#   \__ \ |  __/   <| | | | | | (_| | | | |_| | (_) |
#   |___/_|\___|_|\_\_| |_| |_|\__,_|_| |_(_)_|\___/
#                  <Project name>
#              Created by Jouke Siekman
#             Netherlands 2023 Leerbroek
#                https://siekman.io
#####################################################
## <DETAILS ABOUT FILE>
#####################################################


    - name: Upgrade all packages Debian / Ubuntu Servers
      ansible.builtin.apt:
        upgrade: yes
      when:
        - ansible_pkg_mgr == "apt"

    - name: Upgrade all packages Arch
      ansible.builtin.pacman:
        upgrade: yes
      when:
        - ansible_pkg_mgr == "pacman"

    - name: Upgrade all packages AlmaLinux
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when:
        - ansible_pkg_mgr == "dnf"

    - name: Upgrade all packages CentOS/RetHat Servers
      ansible.builtin.yum:
        name: "*"
        state: latest
      when:
        - ansible_pkg_mgr == "yum"
