#####################################################
# ANSIBLE-PLAYBOOK 
#####################################################
#        _      _                            _
#    ___(_) ___| | ___ __ ___   __ _ _ __   (_) ___
#   / __| |/ _ \ |/ / '_ ` _ \ / _` | '_ \  | |/ _ \
#   \__ \ |  __/   <| | | | | | (_| | | | |_| | (_) |
#   |___/_|\___|_|\_\_| |_| |_|\__,_|_| |_(_)_|\___/                 
#
#              Created by Jouke Siekman
#             Netherlands 2023 Leerbroek
#                https://siekman.io
#
#####################################################
## TASKS : MAIN.YML
#####################################################
---

  - name: Install packages Debian
    include_tasks: install-packages-debian.yml
    when: ansible_os_family == "Debian"
  
  - name: Install packages AlmaLinux - CentOS - RedHat
    include_tasks: install-packages-redhat.yml
    when: ansible_os_family == "RedHat"
  
  - name: Configure snmpd
    include_tasks: configure.yml
  
  - name: Setup and restart services
    include_tasks: services.yml